spring.application.name=hellodemohelo

# 1. Database URL එකට මුලින්ම 'jdbc:' එක දාන්න ඕනේ
spring.datasource.url=jdbc:postgresql://dpg-daf9hif40ujc73a9gb10-a.singapore-postgres.render.com:5432/fastapi_db_pwfw

# 2. Render database එකේ Username එක (Render dashboard එකේ තියෙන විදිහට)
spring.datasource.username=fastapi_db_pwfw_user

# 3. Render database එකේ Password එක (Render එකේ දීපු Password එක මෙතනට දාන්න)
spring.datasource.password=w9qTMwOdD8skaSgpmObNWkPW0g2T7hUJ

# Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true